name: tancent_vap
description: "Video Animation Player from Tencent for Flutter, supports both Android and iOS platforms."
version: 1.0.0+1
homepage: https://github.com/nizwar/tancent_vap_flutter.git

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.laskarmedia.vap
        pluginClass: VapPlugin
      ios:
        package: com.laskarmedia.vap
        pluginClass: VapPlugin
